- name: RabbitMQ
  hosts: rabbitmq
  become: yes
  tasks:
  - name: downloading erlang
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: downloading rabbitmq
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
  
  - name: installing rabbit mq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: Enable and start
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: adding rabbitmq user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: setting permissions
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
