- name: redis
  hosts: redis
  become: yes
  tasks:
  - name: Installing remi release
    ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

  - name: enabling redis remi 6.2
    ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

  - name: Installing redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: Replacing 127.0.0.1 with 0.0.0.0 to allow remote connections
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Replacing 127.0.0.1 with 0.0.0.0 to allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Enable and start redis
    ansible.builtin.service:
      name: redis
      state: restarted
      enabled: yes