- name: web
  hosts: web
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Enabling and starting nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started
  
  - name: removing the data from html directory
    ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

  - name: Download web data
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp/web.zip

  - name: Extract web data into html directory
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Copy roboshop.conf service
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: restarting nginx
    ansible.builtin.systemd_service:
      name: nginx
      state: restarted
      enabled: yes